# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92e7630b5e31d911a26e47d3ff169e3b9da8c3b7187faa4db3416da3e3322aed43ffacc49684df4c7ab4e59a9b367f294e108213d9abcfca6bf831383e65fb6c

test:
  secret_key_base: c895374bdc72454c4e70f6b564233335c6c44f6e055a854444879da5926f27302711dbcd73c72711a410133ca9c873eab1af61023c4a4b63f07d6c52be731705

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
